### ISSUE TITLE
termType rr:IRI in subjectMap

### ISSUE THREAD

**Issue by simeonackermann** [semantifyit/RocketRML#18]
I'm trying to apply a [YARRRML Condition](https://rml.io/yarrrml/spec/#conditions) in the subject. It should only create a subject on a specific condition, but the parser  throws an `???` error from [input-parser/parser.js](https://github.com/semantifyit/RocketRML/blob/master/src/input-parser/parser.js#L204). It seems the termType rr:IRI in subjectMaps are not (yet) supported?!

An example mapping to reproduce this error is:
```
prefixes:
  schema: "http://schema.org/"
  fn: "http://example.com/"
mappings:
  person:
    sources:
      - ['input~jsonpath', '$.persons[*]']
    s: http://example.com/$(firstname)
    condition:
      function: fn:isSet
      parameters:
        - [fn:input, $(public)]
    po:
      - [a, schema:Person]
```

Is there another way to apply conditions on subject generation?

**Comment by ThibaultGerrier** [comment]
Hello
Unfortunately yarrrml conditions are currently not supported. In RML they transform to nested functions, which aren't supported.
Only yarrrml join-conditions are supported (since they are a special condition case)

If the only condition you need is to check if a field is set you can use the json-path filter feature (see https://www.npmjs.com/package/jsonpath-plus for json-path examples)

With your current mapping:
```
prefixes:
  schema: "http://schema.org/"
  fn: "http://example.com/"
mappings:
  person:
    sources:
      - ['input~jsonpath', '$.persons[?(@.public)]']
    s: http://example.com/$(firstname)
    po:
      - [a, schema:Person]
```
will only process the persons where the public field is truthy. (so skip any persons with `"public": false` or without any public field)
